"""
Chapter 1 — Introduction to Investments.
Covers the key concepts from Chapter 1 of the lecture notes:
  - Margin & Short Selling Simulator (interactive widget)
  - Key Terms Glossary (searchable, filterable)
Renders via show() called from app.py.
"""

import streamlit as st


CSS = """
<style>
.cc-section-label {
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #00d4aa;
    margin-bottom: 0.6rem;
}
.cc-section-title {
    font-size: 1.5rem;
    font-weight: 700;
    color: var(--text-color);
    margin-bottom: 0.25rem;
}
.cc-section-desc {
    font-size: 0.95rem;
    color: color-mix(in srgb, var(--text-color) 55%, transparent);
    margin-bottom: 1.5rem;
}
.cc-sim-formula {
    background: var(--secondary-background-color);
    border-left: 3px solid #00d4aa;
    border-radius: 4px;
    padding: 10px 14px;
    font-size: 0.85rem;
    color: color-mix(in srgb, var(--text-color) 60%, transparent);
    margin-bottom: 1rem;
    font-family: 'Courier New', monospace;
}
.cc-badge {
    display: inline-block;
    font-size: 0.68rem;
    font-weight: 600;
    letter-spacing: 0.07em;
    text-transform: uppercase;
    padding: 2px 8px;
    border-radius: 20px;
    margin-bottom: 6px;
}
.cc-badge-securities { background: rgba(0,   212, 170, 0.15); color: #00d4aa; }
.cc-badge-markets    { background: rgba(88,  166, 255, 0.15); color: #58a6ff; }
.cc-badge-trading    { background: rgba(210, 166, 121, 0.15); color: #c89a5a; }
.cc-badge-portfolio  { background: rgba(188, 140, 255, 0.15); color: #bc8cff; }
.cc-term-def {
    font-size: 0.93rem;
    color: color-mix(in srgb, var(--text-color) 85%, transparent);
    line-height: 1.6;
}
.cc-divider {
    border: none;
    border-top: 1px solid color-mix(in srgb, var(--text-color) 12%, transparent);
    margin: 2rem 0;
}
</style>
"""

GLOSSARY = [
    # Securities
    ("Investing",                "Securities",          "Committing resources today to acquire assets expected to generate future benefits."),
    ("Real assets",              "Securities",          "Physical assets (land, buildings, machinery, knowledge) that generate the economy's net income."),
    ("Financial assets",         "Securities",          "Financial contracts (stocks, bonds) that determine the distribution of income generated by real assets."),
    ("Securities",               "Securities",          "Tradable and fungible financial assets; mainly debt and equity."),
    ("Debt securities",          "Securities",          "Securitised borrowing — issuer promises fixed coupon payments and par value at maturity. Also called fixed income."),
    ("Money market",             "Securities",          "Market for debt securities with one year or less to maturity."),
    ("Bonds",                    "Securities",          "Fixed income securities with more than one year to maturity."),
    ("Interest rate risk",       "Securities",          "Risk that rising interest rates reduce the value of fixed income securities."),
    ("Credit risk",              "Securities",          "Risk that the issuer cannot make promised payments."),
    ("Equity securities",        "Securities",          "Common stocks — give holders cash flow rights (dividends) and control rights (voting)."),
    ("Index",                    "Securities",          "A basket of securities tracking the overall development of a market or segment."),
    # Markets & Structure
    ("Primary market",           "Markets & Structure", "Where securities are initially created and sold; issuers raise money from investors."),
    ("Secondary market",         "Markets & Structure", "Where investors trade already-issued securities among themselves."),
    ("Financial intermediaries", "Markets & Structure", "Institutions that connect suppliers and demanders of capital (banks, brokers, funds, exchanges)."),
    ("Direct search market",     "Markets & Structure", "Buyers and sellers find each other directly, with no formal mechanism."),
    ("Brokered market",          "Markets & Structure", "A broker matches buyers and sellers (e.g. primary markets with investment banks)."),
    ("Dealer market",            "Markets & Structure", "A dealer acts as market-maker, buying from sellers and selling to buyers (e.g. bond markets)."),
    ("Auction market",           "Markets & Structure", "Buyers and sellers gather to trade via auction (e.g. stock exchanges)."),
    # Trading
    ("Order book",               "Trading",             "Collection of all outstanding bid and ask orders in a continuous auction market."),
    ("Market order",             "Trading",             "Order to buy at the lowest available ask or sell at the highest available bid — executes immediately."),
    ("Limit order",              "Trading",             "Order to buy or sell at a specific price; waits in the order book until matched."),
    ("Bid-ask spread",           "Trading",             "Difference between the lowest ask price and the highest bid price; the implicit cost of trading."),
    ("Commission",               "Trading",             "Explicit fee paid to a broker for facilitating a trade."),
    ("Buying on margin",         "Trading",             "Borrowing part of the purchase price of a security from a broker to amplify exposure."),
    ("Short selling",            "Trading",             "Selling a security the investor does not own by borrowing it through a broker, profiting from a price decline."),
    # Portfolio Management
    ("Portfolio",                "Portfolio Management","The collection of all an investor's financial assets."),
    ("Asset allocation",         "Portfolio Management","Decision of how much to invest in each asset class (equities, bonds, money market)."),
    ("Security selection",       "Portfolio Management","Decision of which specific assets to hold within each asset class."),
    ("Top-down approach",        "Portfolio Management","Start from asset allocation into broad classes, then select individual securities."),
    ("Bottom-up approach",       "Portfolio Management","Focus on selecting the best individual securities; asset allocation emerges as an outcome."),
]

BADGE_CLASS = {
    "Securities":          "cc-badge-securities",
    "Markets & Structure": "cc-badge-markets",
    "Trading":             "cc-badge-trading",
    "Portfolio Management":"cc-badge-portfolio",
}

CAT_COLOURS = {
    "Securities":          "#00d4aa",
    "Markets & Structure": "#58a6ff",
    "Trading":             "#c89a5a",
    "Portfolio Management":"#bc8cff",
}

CATEGORIES = ["All", "Securities", "Markets & Structure", "Trading", "Portfolio Management"]


def _badge(category: str) -> str:
    cls = BADGE_CLASS.get(category, "cc-badge-securities")
    return f'<span class="cc-badge {cls}">{category}</span>'


def _render_simulator():
    st.markdown('<div class="cc-section-label">Interactive Widget</div>', unsafe_allow_html=True)
    st.markdown('<div class="cc-section-title">Margin &amp; Short Selling Simulator</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="cc-section-desc">'
        "Explore the mechanics and leverage effects of buying on margin and short selling."
        "</div>",
        unsafe_allow_html=True,
    )

    tab_margin, tab_short = st.tabs(["Buying on Margin", "Short Selling"])

    # ── Margin tab ────────────────────────────────────────────────────────────
    with tab_margin:
        st.markdown(
            '<div class="cc-sim-formula">'
            "Total Position = Shares × Price &nbsp;|&nbsp; "
            "Borrowed = Total Position × (1 − Margin%) &nbsp;|&nbsp; "
            "ROI = (ΔPrice × Shares) / Own Equity"
            "</div>",
            unsafe_allow_html=True,
        )

        c1, c2, c3 = st.columns(3)
        with c1:
            m_price  = st.number_input("Asset price ($)", value=100.0, min_value=0.01, step=1.0, key="m_price")
            m_shares = st.number_input("Number of shares", value=100, min_value=1, step=10, key="m_shares")
        with c2:
            m_margin = st.slider("Margin % (own funds)", min_value=10, max_value=100, value=50, step=5, key="m_margin")
            m_move   = st.slider("Price change (%)", min_value=-50, max_value=50, value=10, step=1, key="m_move")
        with c3:
            total_position = m_price * m_shares
            own_equity     = total_position * (m_margin / 100)
            borrowed       = total_position - own_equity
            new_position   = m_price * (1 + m_move / 100) * m_shares
            gain_loss      = new_position - total_position
            roi            = (gain_loss / own_equity) * 100 if own_equity > 0 else 0.0

            st.metric("Total Position", f"${total_position:,.2f}")
            st.metric("Own Equity",     f"${own_equity:,.2f}")
            st.metric("Borrowed",       f"${borrowed:,.2f}")

        col_gl, col_roi = st.columns(2)
        sign = "+" if m_move >= 0 else ""
        col_gl.metric(
            f"Gain / Loss (price {sign}{m_move}%)",
            f"${gain_loss:,.2f}",
            delta=f"${gain_loss:,.2f}",
        )
        col_roi.metric("ROI on own equity", f"{roi:.2f}%", delta=f"{roi:.2f}%")

        if own_equity > 0:
            st.caption(
                f"Leverage ratio: {total_position/own_equity:.1f}× — "
                f"a {sign}{m_move}% price move becomes a {roi:.1f}% return on your equity. "
                "Leverage amplifies both gains and losses."
            )

    # ── Short selling tab ─────────────────────────────────────────────────────
    with tab_short:
        st.markdown(
            '<div class="cc-sim-formula">'
            "Proceeds = Shares × Borrow Price &nbsp;|&nbsp; "
            "Cost to Close = Shares × Current Price &nbsp;|&nbsp; "
            "P&amp;L = Proceeds − Cost to Close &nbsp;|&nbsp; "
            "Return = P&amp;L / Proceeds"
            "</div>",
            unsafe_allow_html=True,
        )

        c1, c2, c3 = st.columns(3)
        with c1:
            s_shares  = st.number_input("Shares borrowed & sold", value=100, min_value=1, step=10, key="s_shares")
            s_borrow  = st.number_input("Price at which sold ($)", value=100.0, min_value=0.01, step=1.0, key="s_borrow")
        with c2:
            s_current = st.number_input("Current price ($)", value=85.0, min_value=0.01, step=1.0, key="s_current")
        with c3:
            proceeds      = s_shares * s_borrow
            cost_to_close = s_shares * s_current
            pnl           = proceeds - cost_to_close
            ret           = (pnl / proceeds) * 100 if proceeds > 0 else 0.0

            st.metric("Proceeds from short sale", f"${proceeds:,.2f}")
            st.metric("Cost to close position",   f"${cost_to_close:,.2f}")

        col_pnl, col_ret = st.columns(2)
        col_pnl.metric("Profit / Loss", f"${pnl:,.2f}", delta=f"${pnl:,.2f}")
        col_ret.metric("Return",        f"{ret:.2f}%",  delta=f"{ret:.2f}%")

        direction = "fallen" if s_current < s_borrow else "risen"
        note = "profit" if pnl >= 0 else "loss"
        st.caption(
            f"The stock has {direction} from ${s_borrow:.2f} to ${s_current:.2f}. "
            f"You realise a {note} of ${abs(pnl):,.2f}. "
            "Note: short sellers face theoretically unlimited losses if the price rises without bound."
        )


def _render_glossary():
    st.markdown("<hr class='cc-divider'>", unsafe_allow_html=True)
    st.markdown('<div class="cc-section-label">Chapter 1 Reference</div>', unsafe_allow_html=True)
    st.markdown('<div class="cc-section-title">Key Terms Glossary</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="cc-section-desc">Search by term or definition. Filter by category.</div>',
        unsafe_allow_html=True,
    )

    col_search, col_filter = st.columns([2, 1])
    with col_search:
        query = st.text_input(
            "Search terms",
            placeholder="e.g. margin, beta, auction…",
            label_visibility="collapsed",
        )
    with col_filter:
        category_filter = st.selectbox(
            "Category",
            CATEGORIES,
            label_visibility="collapsed",
        )

    q = query.strip().lower()

    filtered = [
        (term, cat, defn)
        for term, cat, defn in GLOSSARY
        if (category_filter == "All" or cat == category_filter)
        and (not q or q in term.lower() or q in defn.lower())
    ]

    if not filtered:
        st.info("No terms match your search. Try a different keyword or reset the filter.")
        return

    count = len(filtered)
    st.markdown(
        f'<div class="cc-section-desc" style="margin-bottom:0.8rem">'
        f"{count} term{'s' if count != 1 else ''} found</div>",
        unsafe_allow_html=True,
    )

    for cat in ["Securities", "Markets & Structure", "Trading", "Portfolio Management"]:
        cat_terms = [(t, c, d) for t, c, d in filtered if c == cat]
        if not cat_terms:
            continue

        colour = CAT_COLOURS[cat]
        st.markdown(
            f'<div style="font-size:0.68rem;font-weight:700;letter-spacing:0.12em;'
            f'text-transform:uppercase;color:{colour};margin:1rem 0 0.5rem 0;'
            f'border-bottom:1px solid color-mix(in srgb, var(--text-color) 12%, transparent);'
            f'padding-bottom:4px">{cat}</div>',
            unsafe_allow_html=True,
        )

        for term, cat_, defn in cat_terms:
            with st.expander(term):
                st.markdown(
                    f"{_badge(cat_)}"
                    f'<div class="cc-term-def">{defn}</div>',
                    unsafe_allow_html=True,
                )


def show():
    st.markdown(CSS, unsafe_allow_html=True)
    st.header("Chapter 1 — Introduction to Investments")
    st.caption("Markets, securities, trading mechanics, and the investment process.")

    with st.expander("📖 Concept Overview", expanded=False):
        st.markdown("""
        Chapter 1 lays the conceptual foundations of investment analysis.

        **Real vs Financial Assets**
        The economy's wealth is created by **real assets** — land, machinery, knowledge.
        **Financial assets** (stocks, bonds) are claims on the income those real assets generate;
        they determine who gets paid, not how much is produced.

        **The Investment Process**
        Investors decide *how much* to invest in each asset class (**asset allocation**) and
        *which specific securities* to hold (**security selection**). The **top-down** approach
        starts with allocation; the **bottom-up** approach starts with individual stock picking.

        **Market Structure**
        Securities are born in the **primary market** (IPOs, bond issuance) and traded in the
        **secondary market** (exchanges, OTC). Market types range from informal
        **direct search** to organised **auction markets** with a public order book.

        **Leverage and Short Selling**
        **Buying on margin** lets investors borrow part of a purchase price, amplifying both
        gains and losses. **Short selling** allows profiting from price declines by borrowing
        and selling a security, then buying it back later at (ideally) a lower price.
        """)

    st.divider()
    _render_simulator()
    _render_glossary()
